- name: Upgrade all packages to the latest version
  apt:
    name: "*"
    state: latest

- name: Check if a reboot is needed required
  register: reboot_file
  stat: path=/var/run/reboot-required get_md5=no

- name: Reboot the server
  reboot:
    msg: "Rebooting server after updates"
    connect_timeout: 5
    reboot_timeout: 300
    pre_reboot_delay: 0
    post_reboot_delay: 30
    test_command: uptime
  when: reboot_file.stat.exists